#ifndef LOG_RECORD_H
#define LOG_RECORD_H

#include "config/type.h"
#include "file/block_id.h"
#include "file/page.h"
#include "concurrency/transaction.h"
#include "log/log_manager.h"

#include <memory>
#include <string>
#include <vector>
#include <sstream>

namespace SimpleDB {

enum class LogRecordType {
    INVALID = 0,
    // table heap related
    SETINT,
    SETSTRING,
    // txn related
    CHECKPOINT,
    START,
    COMMIT,
    ROLLBACK, // or called abort
};

/**
* @brief
* LogRecord is a interface that each record implements it
* All operations on table such as Update、Insert、Delete, will be viewed as   
* several SetInt and SetString.
*
* LOG HEADER (record size will be automatically add by logmanager)
* --------------------------------------------
* | LSN | txn_ID | prevLSN | Logtype | IsCLR |
* --------------------------------------------
* For CheckPoint、Commit、Abort、Start
* ----------
* | Header | 
* ----------
* For SetInt
* --------------------------------------------------------------------------
* | Header | FileName.size() | FileName | BlockNum | Old value | New value |
* --------------------------------------------------------------------------
* For SetString
* ----------------------------------------------------------------------------------------------------------------
* | Header | FileName.size() | FileName | BlockNum | Old String Size | Old String | New String Size | New String |
* ----------------------------------------------------------------------------------------------------------------
*/
class LogRecord {

public:

    LogRecord() = default;
    // virtual ~LogRecord() = default;

    lsn_t GetLsn() {
        return lsn_;
    }

    txn_id_t GetTnxID() {
        return txn_id_;
    }
    
    LogRecordType GetRecordType() {
        return type_;
    }

    void SetPrevLSN(lsn_t lsn) {
        prev_lsn_ = lsn;
    }

    lsn_t GetPrevLSN() {
        return prev_lsn_;
    }
    
    void SetCLR() {
        is_clr_ = true;
    }
    
    bool IsCLR() {
        return is_clr_;
    }

    std::string GetHeaderToString() {
        std::string clr;
        if(is_clr_) 
            clr = "CLR";
        std::stringstream os;
        os << "Log ["
           << "lsn: " << lsn_ << " "
           << "txnID: " << txn_id_ << " "
           << "prevLSN: " << prev_lsn_ << " "
           << "LogRecordType: " << static_cast<int>(type_) <<" "
           << clr << "] ";

        return os.str();
    }
        
    virtual std::string ToString() = 0;

    /**
    * @brief 
    */
    virtual void Undo(Transaction *txn) = 0;
    
    /**
    * @brief 
    */
    virtual void Redo(Transaction *txn) = 0;

    /**
    * @brief turn a logrecord object into the byte-sequence
    */
    virtual std::shared_ptr<std::vector<char>> Serializeto() = 0;

    /**
    * @brief turn byte-sequence into a logrecord
    * 
    * @param byte_array a byte array
    */
    static std::shared_ptr<LogRecord> DeserializeFrom(const std::vector<char> &byte_array);

    /**
    * @brief helper function which build a page with log header
    * 
    * @return a built page
    */
    static Page GetHeaderPage(txn_id_t txn_id, LogRecordType type, int is_clr, int record_size);

    /**
    * @brief Get header information through page
    */
    void GetHeaderInfor(Page *p);

    
public: 
    // helper variable
    static constexpr uint32_t HEADER_SIZE = 
            sizeof(lsn_t) + sizeof(txn_id_t) + sizeof(lsn_t) + sizeof(LogRecordType) + sizeof(int);


protected: /* can be accessed by child class, can not be access by other class */
    
    // the corresponding lsn number which generated by logmanager
    lsn_t lsn_{INVALID_LSN};
    // the correspoding transaction_id
    txn_id_t txn_id_;
    // Used to construct a lsn_list
    lsn_t prev_lsn_{INVALID_LSN};
    // LogRecord Type
    LogRecordType type_;
    // is CLR_record ?
    int is_clr_{false};
};


class SetIntRecord : public LogRecord {

public:
    
    SetIntRecord() = default;
    
    SetIntRecord(Page *p);

    SetIntRecord(txn_id_t txn_id,  BlockId block, 
                    int offset, int old_value, int new_value);
    
    void Redo(Transaction *txn) override;
    
    void Undo(Transaction *txn) override;

    std::string ToString() override;

    std::shared_ptr<std::vector<char>> Serializeto() override;
    

    // for debugging purpose
    bool operator ==(const SetIntRecord &obj) const {
        return lsn_ == obj.lsn_ && txn_id_ == obj.txn_id_ && 
                prev_lsn_ == obj.prev_lsn_ && block_ == obj.block_ &&
                new_value_ == obj.new_value_ && old_value_ == obj.old_value_ &&
                record_size_ == obj.record_size_ && is_clr_ == obj.is_clr_;
    }
    
    bool operator !=(const SetIntRecord &obj) const {
        return !(obj == *this);
    }

private:
    
    BlockId block_;
    // the offset in block
    int offset_;
    
    int new_value_;
    
    int old_value_;

    int record_size_;
};

/*
class SetStringRecord : public LogRecord {

};

class CommitRecord : public LogRecord {

};


class CheckpointRecord : public LogRecord {
    
};

class BeginRecord : public LogRecord {

};

class RollbackRecord : public LogRecord {
    
};
*/
} // namespace SimpleDB

#endif